### ISSUE TITLE
Join the Extendscript org?

### ISSUE THREAD

**Issue by ff6347** [EugenTepin/ps-scripting-es5shim#1]
Hey @EugenTepin I saw your repo and went ahead and invited you to our GitHub Extendscript org. Would be cool if you join. It also would be cool if we combine our efforts to create an Extendscript shim. I have a repo like this and others have as well. Will you join forces with us?

**Comment by EugenTepin** [comment]
Hi, I am already [joined ](https://github.com/orgs/ExtendScript/people). And i am ready to join forces in creating Extendscript shim.  Do you have any ideas how to do that?

**Comment by ff6347** [comment]
Sure. We create team on extendscript org and throw together what we have on shims.  before we start collecting the source we should create a list what shims we need. You actually started that already in your repo [here](https://github.com/EugenTepin/ps-scripting-es5shim/blob/master/index.js).  I'll go ahead and do that. Should we make a fork of your repo or just copy over the sources?

**Comment by ff6347** [comment]
We just need some build script to concat them all.

**Comment by ff6347** [comment]
Lets take this discussion to that new repo https://github.com/ExtendScript/extendscript-es5-shim
